{
 "title": "wal-dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "query": { "query": "label_values(namespace)" } },
   {
    "name": "pipeline",
    "query": {
     "query": "label_values({namespace=~\"$namespace\"}, pipeline)"
    }
   },
   {
    "name": "vertex",
    "query": {
     "query": "label_values({namespace=~\"$namespace\", pipeline=~\"$pipeline\"}, vertex)"
    }
   },
   {
    "name": "replica",
    "query": {
     "query": "label_values({namespace=~\"$namespace\", pipeline=~\"$pipeline\",vertex=~\"$vertex\"}, replica)"
    }
   },
   { "name": "datasource", "label": "data source", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Traffic Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "new WAL Files per second",
   "type": "timeseries",
   "description": "Number of new WAL files created per second",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(pbq_aligned_wal_files_total{namespace=\"$namespace\", pipeline=\"$pipeline\", vertex=\"$vertex\", replica=~\"$replica\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "new WAL Entries per second",
   "type": "timeseries",
   "description": "no. of new WAL entries written",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "rate(pbq_aligned_wal_entries_total{namespace=\"$namespace\", pipeline=\"$pipeline\", vertex=\"$vertex\", replica=~\"$replica\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Latency Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "WAL File Sync Wait Time",
   "type": "timeseries",
   "description": "WAL File Sync Wait Time in millisecond",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(pbq_aligned_wal_file_sync_wait_time_bucket{namespace=\"$namespace\", pipeline=\"$pipeline\", vertex=\"$vertex\", replica=~\"$replica\"}[$__rate_interval])))",
     "legendFormat": "{{le}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(pbq_aligned_wal_file_sync_wait_time_bucket{namespace=\"$namespace\", pipeline=\"$pipeline\", vertex=\"$vertex\", replica=~\"$replica\"}[$__rate_interval])))",
     "legendFormat": "{{le}}"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(pbq_aligned_wal_file_sync_wait_time_bucket{namespace=\"$namespace\", pipeline=\"$pipeline\", vertex=\"$vertex\", replica=~\"$replica\"}[$__rate_interval])))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "WAL Entry Write Time",
   "type": "timeseries",
   "description": "WAL Entry Write Time in millisecond",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(pbq_aligned_wal_entry_write_time_bucket{namespace=\"$namespace\", pipeline=\"$pipeline\", vertex=\"$vertex\", replica=~\"$replica\"}[$__rate_interval])))",
     "legendFormat": "{{le}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(pbq_aligned_wal_entry_write_time_bucket{namespace=\"$namespace\", pipeline=\"$pipeline\", vertex=\"$vertex\", replica=~\"$replica\"}[$__rate_interval])))",
     "legendFormat": "{{le}}"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(pbq_aligned_wal_entry_write_time_bucket{namespace=\"$namespace\", pipeline=\"$pipeline\", vertex=\"$vertex\", replica=~\"$replica\"}[$__rate_interval])))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Error Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Errors per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "rate(pbq_aligned_wal_errors{namespace=\"$namespace\", pipeline=\"$pipeline\", vertex=\"$vertex\"}[$__rate_interval])",
     "legendFormat": "{{error}}"
    }
   ]
  },
  { "title": "WAL State Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Active WAL files",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "pbq_aligned_active_wal_files_total{namespace=\"$namespace\", pipeline=\"$pipeline\", vertex=\"$vertex\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}